### PR TITLE
Replace ExtendedKeyUsageNames by IDs resolves #215

### LINKED ISSUE #215: DSC Certificate Creation: New-SelfSignedCertificateEx fails
New-SelfSignedCertificateEx fails on my setup, with an unknown parameter exception.
It doesn't take the names of the EKUs. I guess this is again some localization problem...

Solution is for me, to replace the names by the EKU IDs. 

Will create a pull request in a sec.

### PR DESCRIPTION
**Pull request by m0rgenthau**
Replaced the EKU names by their assigned IDs to resolve #215

---
This change is [Reviewable](https://reviewable.io/reviews/plagueho/labbuilder/216)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Another excellent fix there. Are the KU's OK being names as well?

Also, are you able to add a line into the ### Unreleased (if it isn't there just add it) section at the top of \Docs\ChangeList.md - that way we can figure out all the changes in each release.

Your branch does have merge conflicts though - so GitHub won't let me merge this until they are fixed.

The conflict should be easy to resolve:
https://githowto.com/resolving_conflicts

It would be easy enough for my to just copy your fix into the code, but merge conflicts are one of those things that are just handy to know how to fix. Besides, then you get credit for the fix in the code - :smiley:

**Comment by m0rgenthau** [comment]
Okay, I guess I stuffed up... 10 commits for a minor change...
Well, thanks for the advice, i'm pretty new to this, hope i got it finally correct

**Comment by PlagueHO** [comment]
Oh no - that's no stuff up! Completely normal behavior - it happens all the time - especially because I'm working on the base branch all the time, so I'd be generally surprised you didn't run into a merge conflict. 
And trust me, lots of commits for a small change is very common (you should see some of my commits to the community DSC resources - 20+ commits for a small change :smile: )

**Comment by PlagueHO** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/plagueho/labbuilder/216)*

**Pull request merged**
