### PR TITLE
Update with DataVHD Copy

### PR DESCRIPTION
**Pull request by DragonReach**
Adding code to copy folder/files onto Data VHDs

### CODE REVIEW

**Comment by PlagueHO** [comment]
There appear to be some conflicts with this PR - it won't let me merge till they are resolved.

**Comment by DragonReach** [comment]
I thought I had resolved all conflicts - I'll go back and see what shows up.

**Comment by DragonReach** [comment]
Something is messed up, every 30 minutes or so Git is showing I need to do a push, but nothing changes.

**Comment by DragonReach** [comment]
not sure of issue here, new pull request with fixes already applied

**Pull request closed without merging**
