### PR TITLE
Fix to DC_SECONDARY.DSC.ps1 throws InvalidOperationException #378

### LINKED ISSUE #1: Multiple errors with simple config
Used the Forest Root and DHCP sample as a starting point, seems documentation is lacking and you start from the assumption of VMs running to pull the template VHDs from.  I have sysprepped images and see multiple errors that aren't helpful.  Example below. -- I have no idea what to put in the XML for this value as there is no sample that uses it and a cursory view of the code doesn't provide any real enlightenment 

Test-Path : Cannot bind argument to parameter 'Path' because it is an empty string.
At D:\HVFCLab\LabBuilder.psm1:456 char:31
+     If (-not (Test-Path -Path $FullConfigPath))
+                               ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Test
   PathCommand

in addition this error makes no sense to me - 
Get-LabVMTemplates : The Template Source VHD 'Template Windows Server 2016 Datacenter Full' in Template
'Win2016-DataCenterFULLG2.VHDX' could not be found.
At D:\HVFCLab\LabBuilder2.psm1:4341 char:20
+     $VMTemplates = Get-LabVMTemplates `
+                    ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-LabVMTemplates], InvalidOperationException
    + FullyQualifiedErrorId : TemplateSourceVHDNotFoundError,Get-LabVMTemplates

It seems to be putting the wrong value - when I tried to introduce a pause it never showed in enumerating the templates. 

A sample XML that you actually use and an idea of the existing environment it is based on would help.  This is a really cool idea and I would love to get use out of it.  Sorry if this is something simple that I am overlooking

### LINKED ISSUE #3: Add VM Computer name to credentials used to connect to VM
Have to had new VM into trusted host. - added code - In addition set credentials to include OS Name in Function Wait-LabVMInit

Actual fix

```powershell
$Username = $VM.ComputerName + '\Administrator'
    Write-Verbose $Username
    [PSCredential] $AdmininistratorCredential = New-Credential `
        -Username $Username `
        -Password $VM.AdministratorPassword
```

### LINKED ISSUE #378: DC_SECONDARY.DSC.ps1 throws InvalidOperationException
When trying to deploy a secondary DC using the DC_SECONDARY.DSC.ps1 DSC template, an exception is thrown as per below:

```
VERBOSE: [12:25:52]: Preparing to compile DSC Config 'DC_SECONDARY' for VM 'AD 3 DC2'.
PSDesiredStateConfiguration\Node : A parameter cannot be found that matches parameter name 'ArgumentName'.
At C:\VM\AD 3\AD 3 DC2\LabBuilder Files\DSC.ps1:36 char:5
+     Node $AllNodes.NodeName {
+     ~~~~
    + CategoryInfo          : InvalidArgument: (:) [PSDesiredStateConfiguration\node], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : NamedParameterNotFound,PSDesiredStateConfiguration\node

Compilation errors occurred while processing caonfiguration 'DC_SECONDARY'. Please review the errors reported in error stream and modify your configuration code appropriately.
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:3917 char:5
+     throw $ErrorRecord
+     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (DC_SECONDARY:String) [], InvalidOperationException
    + FullyQualifiedErrorId : FailToProcessConfiguration
```

This occurs on instantiation of the `System.Management.Automation.PSCredential` object, because the parameter `-ArgumentName` is passed to `New-Object`, although there is no parameter with that name. I believe this should be `-ArgumentList`, which is present in other DSC templates. The DC_SECONDARY template works when this is corrected.

I've searched for all instances of -ArgumentName in the repo, and it only appears in this DSC template.

### PR DESCRIPTION
**Pull request by stuart938503**
Thanks for submitting a Pull Request to the LabBuilder project!

Please make sure you have read the [Contributing.md](\.github\CONTRIBUTING.md) document.

# Bug Fixes

Use the pound / hash sign to indicate which GitHub issues this Pull Request fixes, if applicable.

- Fixes #378

For review @PlagueHO - apologies if there is an issue with this pull request - first one I have done.

---
This change is [Reviewable](https://reviewable.io/reviews/plagueho/labbuilder/379)

### CODE REVIEW

**Review by johlju — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/plagueho/labbuilder/379#-:-MnLjmEM0IrudlKnTCcn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stuart938503)

**Review by PlagueHO — APPROVED** [review]
Hi @stuart938503 - great stuff. Can you add an entry to the CHANGELOG.md for this fix?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/plagueho/labbuilder/379#-:-MnRoEhyDY9K19MAkJPx:b-97uh0o)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stuart938503)

**Comment by stuart938503** [comment]
Hi @PlagueHO  - I believe that is done. Let me know if you need more.

**Comment by PlagueHO** [comment]
Just going to fix the pipelines (agent versions need to be updated).

**Comment by PlagueHO** [comment]
Hi @stuart938503 - I've fixed the build pipelines, but it's caused a merge conflict. Can you just fix that and I'll get this through.

**Review by PlagueHO — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/plagueho/labbuilder/379)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stuart938503)

**Review by PlagueHO — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/plagueho/labbuilder/379#-:-MnWrNBjBFeWvW2ViKn9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stuart938503)

**Pull request merged**
