### PR TITLE
Nano ODJ extension and support for Offline

### PR DESCRIPTION
**Pull request by MS-MatthewWalker**
@PlagueHO 

Extended LABVM class to support Offline Domain Join and added an option in the install-lab function to allow for offline setup - offline option requires all modules be in the module directory or path.

---
This change is [Reviewable](https://reviewable.io/reviews/plagueho/labbuilder/278)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Oh wow! Nice work @MS-MatthewWalker ! I was literally just about to do some work on this (it's a public holiday here in NZ so I have some time) and you beat me to it. Guess I'll go work on some of the other issues :grin:

**Comment by PlagueHO** [comment]
@MS-MatthewWalker - I've made a few fixes to this as it would throw errors if the ODJ file actually exist for a Nano server (which is possible). There was also some missing messages and some unnecessary code. I think everything should still work, but I haven't written any unit tests so I can't be sure.

I'm thinking I might at some point rework the code that copies files to VM's to make them more generic (lots of duplicated code all over the place). But I'll worry about that later.

You'll want to update your fork with my updates.

**Comment by PlagueHO** [comment]
@MS-MatthewWalker - I have one more question about this:

Would it cause you any problems if I name the ODJ file with a standard file name rather than ```$($VM.ComputerName).txt```? E.g. ODJRequest.txt?

That way we can simplify a lot of the code. This doesn't seem like it would cause a problem because the ODJRequest.txt would always be only on the node or in the LabBuilderFiles folder for each VM.

**Comment by MS-MatthewWalker** [comment]
Right now a default name would break my implementation - I'm copying the ODJFiles to a singular location and to copy the proper file to the proper VM I am using the computername to keep them unique.

**Comment by PlagueHO** [comment]
@MS-MatthewWalker - I should have been more clear. What I was thinking was that when the ODJ file is copied into the LabBuilder Files folder (from wherever it comes from) it would be renamed from the ComputerName.txt to the static name. This would mean that we could simplify the code.

Although I'm still trying to work out how to completely automate the Nano Server ODJ process in a Lab as I'm considering enabling the Nano Servers to go direct to the AD controller (via a SMB share) and collect the ODJ file. This would mean that the join would be performed without requiring any special interaction with the host. At the moment the process seems a bit fragile. Will keep thinking on it!

**Comment by MS-MatthewWalker** [comment]
@PlagueHO  - Ah that makes sense, and I can definitely see it being easier code wise.  To give you an idea of what I am doing you can check out https://github.com/MS-MatthewWalker/LabBuilderLabs/tree/Dev i have setuplab script there that I am using.  It's ugly but it works.

**Pull request merged**
