### PR TITLE
fixing location of labbuilderconfig-schema.md

### PR DESCRIPTION
**Pull request by gengle**
moved `labbuilderconfig-schema.md` to correct docs folder

---
This change is [Reviewable](https://reviewable.io/reviews/plagueho/labbuilder/313)

### CODE REVIEW

**Comment by gengle** [comment]
@PlagueHO this sounds like a great idea.  I'll make those changes and we can squash my commits if things look good.

**Comment by PlagueHO** [comment]
Cool! Thanks @gengle! Awesome to have the help :grin: Don't get as much time on these projects as I used to.

**Comment by gengle** [comment]
@PlagueHO I took a stab at the conversion.  Let me know if you'd like me to squash my commits.

**Comment by gengle** [comment]
I see there is an error

```
Error: 4/16/2019 1:58:02 AM: 
At D:\a\1\s\psakefile.ps1:233 char:13
 +     $null = Copy-Item -Path (Join-Path -Path $ProjectRoot -ChildPath  ...
 +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [<<==>>] Exception: Cannot find path 'D:\a\1\s\src\docs' because it does not exist.
```

I'll look into this

**Comment by PlagueHO** [comment]
@gengle - I think you can go ahead and delete that line as it won't be needed any more.

**Pull request merged**
