### PR TITLE
Fix for Template prefix value  prepended to VHDs

### LINKED ISSUE #262: VHD Template Prefix not applying
Before submitting your issue for the LabBuilder project, please take a moment to provide the following details:

- [5.1.14393.0 ] Verison of PowerShell you're using
- [ Console Host] PowerShell host you're using (eg. Console Host, ISE, Visual Studio)
- [Win10 Insider Build 14393 ] Operating system you're running
- [MSFT-MWalker branch ] Version of LabBuilder you're using (use `Get-Module -Name LabBuilder`)

Review of VHDTemplate.ps1 indicates the specified template prefix will not apply 

```
        # Add the template prefix to the VHD name.
        if (([String]::IsNullOrWhitespace($TemplatePrefix)))
        {
             $VHDPath = Join-Path `
                -Path (Split-Path -Path $VHDPath)`
                -ChildPath ("$TemplatePrefix$(Split-Path -Path $VHDPath -Leaf)")
        } # if

```
will only run the code block if no prefix is specified, simple fix below

```
        # Add the template prefix to the VHD name.
        if (!([String]::IsNullOrWhitespace($TemplatePrefix)))
        {
             $VHDPath = Join-Path `
                -Path (Split-Path -Path $VHDPath)`
                -ChildPath ("$TemplatePrefix$(Split-Path -Path $VHDPath -Leaf)")
        } # if
```

### PR DESCRIPTION
**Pull request by MS-MatthewWalker**
# Bug Fixes

- Fixes #262 

@PlagueHO  -

---
This change is [Reviewable](https://reviewable.io/reviews/plagueho/labbuilder/263)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Cool!  Thanks heaps for all your work on this @ms-matthewwalker. I'll review after work tonight. Sorry I've not been doing much on this lately. Between work and helping on the dsc community hqrm stuff I've had almost no time.

**Comment by MS-MatthewWalker** [comment]
Hold off on this, been talking to @ericreiss and there is a bit more to do

@PlagueHO  - also working on timing issue he saw and multiple adds to trusted hosts

**Comment by PlagueHO** [comment]
Ok! No worries. I have to fix some unit tests on this tonight anyway - so that the AppVeyor tests pass.

**Comment by MS-MatthewWalker** [comment]
@PlagueHO  What is your opinion on changing this to use the LabId value rather than a separate template value?

**Comment by PlagueHO** [comment]
@MS-MatthewWalker - sorry about taking so long. I pretty much just rewrote the xCertificate DSC resource from scratch because of the massive amount of tech debt on it. TBH - it should never have been allowed to be released in the MSFT DSC Resource Kit. Took me about 30 hours of work to fix up. 

Anyway, to your question: Wouldn't this mean that multiple Labs couldn't share the same TemplateVHD files?

**Comment by MS-MatthewWalker** [comment]
@PlagueHO  I hadn't considered that scenario -- makes sense that way.

**Comment by PlagueHO** [comment]
Doh! Sorry, I've been so busy working on fixing xStorage (even working on the Issue you raised in it). I'll review this tonight.

**Comment by MS-MatthewWalker** [comment]
ACK -- I knew I should have forked this - Didn't mean to include all of those changes in there - This breaks some of your previous setups but was necessary for me to get some things to work according to the requirements I had.

**Comment by PlagueHO** [comment]
Good work @MS-MatthewWalker - looks good. So to confirm, this is to basically remove the space between the LabId and object names (VM, Adapter, Switch, Template etc). Is that correct?

I'm think though, that this will break any existing labs that are built using names that include a space. So that is all my currently provisioned labs :smile:. Is it worth implementing a compatibility mode switch that allows old version labs to still be worked with?

**Comment by MS-MatthewWalker** [comment]
Yes that is the original change in there, on top of that a few other changes were adopted - Not sure if you are going to want them so I may need to kill the pull request and revert back 

In addition to removing the space after LABID, I modified the way instance count works (I'm assuming that is causing the failures)  For example if you have an InstanceCount of 1, VM and ComputerName are not modified however anything with an InstanceCount greater than 1 will append the numerical value to each created VM and ComputerName - previous implementation would only append the numerical value to the 2nd and higher instances - made for some inconsistencies in computer names from a management perspective.

**Comment by MS-MatthewWalker** [comment]
LABID for current existing labs could be simply modified by adding a space to the end and then all existing labs should continue to work.

**Comment by PlagueHO** [comment]
Ok cool. I'll get this merged tonight and manually convert my Labs and see how it goes :) I've got an HA   experimental lab I use on a daily basis that will be my motivator for the conversion :)

**Comment by PlagueHO** [comment]
Oh also,  I'm working on the issue you raised on xstorage at the moment. That resoruce is pretty much getting a complete rewrite.

**Comment by PlagueHO** [comment]
Ok - I'm going to bite the bullet on this one and fix up all my labs manually. I'll need to put some work into getting the tests to pass. So.... wish me luck :grin:

**Comment by PlagueHO** [comment]
Unfortunately there are some bugs in this I'll need to fix. There are still many places where there will be a space between the LabId and the Element name - this results in inconsistencies with Labs - sometimes there is a space and other times there isn't. Makes it much harder to manage. I'll do what I can to resolve the issues, but I may have to back the change out. 😞

**Comment by PlagueHO** [comment]
Ok! I've fixed up the unit tests so they're all passing and removed the space from Lab Management switch name (when a LabId is used).

I've updated all the samples to include a space at the end of the LabId so they will still work on any existing labs. So if a LabId setting includes a trailing space it will still behave like it always has and not break any existing labs. This is still a breaking change though. So I expect there will be other issues.

**Pull request merged**
