### PR TITLE
Fixed check for Binding Adapter, if multiple External VM Switches exist

### PR DESCRIPTION
**Pull request by m0rgenthau**
Fixing #196 - check for usage of binding adapter fails, if you already have multiple external vm switches

---
This change is [Reviewable](https://reviewable.io/reviews/plagueho/labbuilder/198)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[LabBuilder/LabBuilder.psm1, line 1270 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/198#-KFR8Gx_6IrDmf7Nc9fq:-KFR8GxaH1knSSaTnvhO:-1491217798) ([raw file](https://github.com/plagueho/labbuilder/blob/0fad651d0cfe514dbea0e237b4369cc3bf50b7ad/LabBuilder/LabBuilder.psm1#L1270)):*
To be safe could you add the line:
```powershell
$MacAddress = @()
```
before the loop?

That will ensure the $MacAddress variable is declared as an empty array before we use it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/plagueho/labbuilder/198)*

**Comment by PlagueHO** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/plagueho/labbuilder/198)*

**Comment by m0rgenthau** [comment]
Yeah, bad habits i guess... 
Fixed that, thanks for having an eye on that!

**Comment by PlagueHO** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/plagueho/labbuilder/198#-:-KFfSqjImYD0H-vIk0Uv:1417088721)*

**Comment by PlagueHO** [comment]
I just realized - your branch has merge conflicts that need to be resolved before Git will allow it to be merged. https://githowto.com/resolving_conflicts

There are some unit test failures, but I'll resolve those by updating the unit tests.

**Comment by PlagueHO** [comment]
In an effort to get this one resolved for you I just copied and pasted your changes in. However, I had done some work on the ExposeVirtualizationExtensions last week so your change to that code wasn't required (which is where the Merge conflict was probably occurring I think).

This also meant that I could update the Unit tests at the same time to resolve the failure :) I hope this is OK? Just wanted to get this out ASAP as I was working on resolving lots of other bits and pieces at the same time.

**Comment by m0rgenthau** [comment]
That's great, thanks for fixing this for me!
Von meinem iPhone gesendet

**Comment by PlagueHO** [comment]
I manually merged this one.

**Pull request closed without merging**
