### PR TITLE
Added VM Version and Generation support fixed Shared VHDX  Fixes #255

### LINKED ISSUE #255: Can't create generation 1 VM
Section for creating a VM only creates Generation 2 VMs, the VHD creation will create both UEFI boot and BIOS boot images, but the VM creation is hard set to only create Generation 2. 

Tried to add the Functionality to the VMTemplate and VM modules, but generates error as below 

```
The property 'Generation' cannot be found on this object. Verify that the property exists and can be set.
At D:\Scripts\lib\public\vmtemplate.ps1:266 char:13
+             $VMTemplate.Generation = $Template.generation
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException
```

Code added to VMTemplate.ps1

```
        if ($Template.generation)
        {
            $VMTemplate.generation = $Template.generation
        }
        elseif (-not $Template.generation)
        {
            $VMTemplate.generation = 2
        } # if
```

not finding an object definition that would prevent this from working.

### PR DESCRIPTION
**Pull request by MS-MatthewWalker**
Thanks for submitting a Pull Request to the LabBuilder project!

Please make sure you have read the [Contributing.md](\.github\CONTRIBUTING.md) document.

# Bug Fixes

- Fixes #255 

# Improvements / Enhancements

* Added support for Version of VM - Only works on latest Windows 10 builds post 14352
* Added support for generation of VM so Generation 1 VMs can now be created
* Fixed issue with Shared VHDX that prevented their creation. - removed unnecessary if statement
* Updated SCHEMA for information on Version and Generation
* Fixed several typos in comment sections
* DSC resources created for working with composite DSC resources - non-functional at this time

@PlagueHO

---
This change is [Reviewable](https://reviewable.io/reviews/plagueho/labbuilder/256)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Looking really awesome - except for the two missing DSC Library files (go figure)? If you can just drop them into your repo and push them then I should be able to merge your branch! Thank you heaps for the really great bug fixes in there. Awesome stuff.

---

Reviewed 30 of 30 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[LabBuilder/dsclibrary/MEMBER_BRANCHCACHE_HOST.DSC.ps1, line 0 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLot6mMYiL5Jqmw0GRl:-KLot6mMYiL5Jqmw0GRm:-1359380197) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/dsclibrary/MEMBER_BRANCHCACHE_HOST.DSC.ps1#L0)):*
Is there a reason this file was deleted? I'm guessing just a mistake somewhere a long the line. Are you able to add it back to your branch?

---

*[LabBuilder/dsclibrary/MEMBER_FAILOVERCLUSTER_DHCP.DSC.ps1, line 0 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLotLrP4l8JI4xyJ384:-KLotLrP4l8JI4xyJ385:909291031) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/dsclibrary/MEMBER_FAILOVERCLUSTER_DHCP.DSC.ps1#L0)):*
Same with this file - was it deleted by mistake? Or just Git being annoying (which it can be)!

---

*[LabBuilder/DSCLibrary/Modules/LabDSCResources.psd1, line 7 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLotWnmBVvdy0Z0V4DZ:-KLotWnmBVvdy0Z0V4D_:-1328950512) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/DSCLibrary/Modules/LabDSCResources.psd1#L7)):*
> ```PowerShell
> RootModule=xJoinDomain.DSC.Schema.psm1
> RootModule=xNPSServer.DSC.Schema.psm1
> RootModule=xRemoteAccessServer.DSC.Schema.psm1
> ```

Needs a CRLF at the end of this line.

---

*[LabBuilder/DSCLibrary/Modules/MyDSCResources/xCertAuthorityServer/xCertAuthorityServer.DSC.Schema.psd1, line 1 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLot_KmC_WaU_EnLVWw:-KLot_KmC_WaU_EnLVWx:635383074) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/DSCLibrary/Modules/MyDSCResources/xCertAuthorityServer/xCertAuthorityServer.DSC.Schema.psd1#L1)):*
> ```PowerShell
> RootModule=xCertAuthorityServer.DSC.Schema.psm1
> ```

CRLF here too :smile:

---

*[LabBuilder/DSCLibrary/Modules/MyDSCResources/xDC/xDC.DSC.Schema.psd1, line 1 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLotf0xUH0JUIsbI4cy:-KLotf0xUH0JUIsbI4cz:635383074) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/DSCLibrary/Modules/MyDSCResources/xDC/xDC.DSC.Schema.psd1#L1)):*
> ```PowerShell
> RootModule=xDC.DSC.Schema.psm1
> ```

CRLF here too :smile:

---

*[LabBuilder/DSCLibrary/Modules/MyDSCResources/xDHCPServer/xDHCPServer.DSC.Schema.psd1, line 1 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLotjabv5Pxk6QVmLUM:-KLotjabv5Pxk6QVmLUN:635383074) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/DSCLibrary/Modules/MyDSCResources/xDHCPServer/xDHCPServer.DSC.Schema.psd1#L1)):*
> ```PowerShell
> RootModule=xDHCPServer.DSC.Schema.psm1
> ```

CRLF here too :smile:

---

*[LabBuilder/DSCLibrary/Modules/MyDSCResources/xFileServer/xFileServer.DSC.Schema.psd1, line 1 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLotn52bOLp5Gi2aGT5:-KLotn52bOLp5Gi2aGT6:635383074) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/DSCLibrary/Modules/MyDSCResources/xFileServer/xFileServer.DSC.Schema.psd1#L1)):*
> ```PowerShell
> RootModule=xFileServer.DSC.Schema.psm1
> ```

CRLF here too :smile:

---

*[LabBuilder/DSCLibrary/Modules/MyDSCResources/xJoinDomain/xJoinDomain.DSC.Schema.psd1, line 1 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLotui3Uh21B1196mcf:-KLotui3Uh21B1196mcg:635383074) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/DSCLibrary/Modules/MyDSCResources/xJoinDomain/xJoinDomain.DSC.Schema.psd1#L1)):*
> ```PowerShell
> RootModule=xJoindomain.DSC.Schema.psm1
> ```

CRLF here too :smile:

---

*[LabBuilder/DSCLibrary/Modules/MyDSCResources/xJoinDomain/xJoinDomain.DSC.Schema.psm1, line 72 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLotx8WnIO4__ETRQW3:-KLotx8WnIO4__ETRQW4:635383074) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/DSCLibrary/Modules/MyDSCResources/xJoinDomain/xJoinDomain.DSC.Schema.psm1#L72)):*
> ```PowerShell
>         }
>     
> }
> ```

CRLF here too :smile:

---

*[LabBuilder/DSCLibrary/Modules/MyDSCResources/xNPSServer/xNPSServer.DSC.Schema.psd1, line 1 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLou-V4bbj8Qlw7QH_i:-KLou-V4bbj8Qlw7QH_j:635383074) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/DSCLibrary/Modules/MyDSCResources/xNPSServer/xNPSServer.DSC.Schema.psd1#L1)):*
> ```PowerShell
> RootModule=xNPSServer.DSC.Schema.psm1
> ```

CRLF here too :smile:

---

*[LabBuilder/DSCLibrary/Modules/MyDSCResources/xRemoteAccessServer/xRemoteAccessServer.DSC.Schema.psd1, line 1 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLou35K5o6wCIarjIUm:-KLou35K5o6wCIarjIUn:635383074) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/DSCLibrary/Modules/MyDSCResources/xRemoteAccessServer/xRemoteAccessServer.DSC.Schema.psd1#L1)):*
> ```PowerShell
> RootModule=xRemoteAccessServer.DSC.Schema.psm1
> ```

CRLF here too :smile:

---

*[LabBuilder/lib/private/utils.ps1, line 370 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLouLYbGYGjlu0H0yKZ:-KLouLYbGYGjlu0H0yK_:988224265) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/lib/private/utils.ps1#L370)):*
> ```PowerShell
>     {
>         WriteMessage -Message ($LocalizedData.EnablingWSManMessage)
>         Start-Service WSMan
> ```

I don't think this line is correct. The WSMan service is actually called WinRM. But it won't be able to start unless Remoting has been initialized, which is done by the next command (Set-WSManQuickConfig).

---

*[LabBuilder/lib/public/vm.ps1, line 388 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLowUU99BDcUTSEu2GE:-KLowUUCvhKIeg2oSwDZ:1663273988) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/lib/public/vm.ps1#L388)):*
> ```PowerShell
>                 # Get the Support Persistent Reservations
>                 $NewDataVHD.SupportPR = ($VMDataVhd.SupportPR -eq 'Y')
>                <# if ($NewDataVHD.SupportPR -and -not $NewDataVHD.Shared) # this isn't necessary Support PR is the only setting required.
> ```

You can go ahead and delete this whole block if you like - good catch! That is why it is great having a Hyper-V/Cluster expert on this :smile:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-:-KLox741Js-HlsQEoxUN:615491979)*

**Comment by MS-MatthewWalker** [comment]
No idea what happened with those two files,  I haven't messed with them so no idea when they disappeared. 

Added all the CRLFs 

---

Review status: 21 of 31 files reviewed at latest revision, 14 unresolved discussions.

---

*[LabBuilder/DSCLibrary/Modules/LabDSCResources.psd1, line 7 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLotWnmBVvdy0Z0V4DZ:-KLqIjTiA7AJx-p7-B5i:-499146009) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/DSCLibrary/Modules/LabDSCResources.psd1#L7)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Needs a CRLF at the end of this line.
</details>
Done.

---

*[LabBuilder/DSCLibrary/Modules/MyDSCResources/xCertAuthorityServer/xCertAuthorityServer.DSC.Schema.psd1, line 1 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLot_KmC_WaU_EnLVWw:-KLqIkxnzHjyBT_VZlDn:-499146009) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/DSCLibrary/Modules/MyDSCResources/xCertAuthorityServer/xCertAuthorityServer.DSC.Schema.psd1#L1)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> CRLF here too :smile:
</details>
Done.

---

*[LabBuilder/DSCLibrary/Modules/MyDSCResources/xDC/xDC.DSC.Schema.psd1, line 1 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLotf0xUH0JUIsbI4cy:-KLqIm54QWxBmYsER9dj:-499146009) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/DSCLibrary/Modules/MyDSCResources/xDC/xDC.DSC.Schema.psd1#L1)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> CRLF here too :smile:
</details>
Done.

---

*[LabBuilder/DSCLibrary/Modules/MyDSCResources/xDHCPServer/xDHCPServer.DSC.Schema.psd1, line 1 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLotjabv5Pxk6QVmLUM:-KLqInSeE39TNMC2GSfT:-499146009) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/DSCLibrary/Modules/MyDSCResources/xDHCPServer/xDHCPServer.DSC.Schema.psd1#L1)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> CRLF here too :smile:
</details>
Done.

---

*[LabBuilder/DSCLibrary/Modules/MyDSCResources/xFileServer/xFileServer.DSC.Schema.psd1, line 1 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLotn52bOLp5Gi2aGT5:-KLqIotFdgeqP4CoeMsj:-499146009) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/DSCLibrary/Modules/MyDSCResources/xFileServer/xFileServer.DSC.Schema.psd1#L1)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> CRLF here too :smile:
</details>
Done.

---

*[LabBuilder/DSCLibrary/Modules/MyDSCResources/xJoinDomain/xJoinDomain.DSC.Schema.psd1, line 1 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLotui3Uh21B1196mcf:-KLqIqLmC3uHkM_C92Vd:-499146009) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/DSCLibrary/Modules/MyDSCResources/xJoinDomain/xJoinDomain.DSC.Schema.psd1#L1)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> CRLF here too :smile:
</details>
Done.

---

*[LabBuilder/DSCLibrary/Modules/MyDSCResources/xJoinDomain/xJoinDomain.DSC.Schema.psm1, line 72 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLotx8WnIO4__ETRQW3:-KLqIs3el5LEZYszudl4:-499146009) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/DSCLibrary/Modules/MyDSCResources/xJoinDomain/xJoinDomain.DSC.Schema.psm1#L72)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> CRLF here too :smile:
</details>
Done.

---

*[LabBuilder/DSCLibrary/Modules/MyDSCResources/xNPSServer/xNPSServer.DSC.Schema.psd1, line 1 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLou-V4bbj8Qlw7QH_i:-KLqItgodDJFQXp2F9_1:-499146009) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/DSCLibrary/Modules/MyDSCResources/xNPSServer/xNPSServer.DSC.Schema.psd1#L1)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> CRLF here too :smile:
</details>
Done.

---

*[LabBuilder/DSCLibrary/Modules/MyDSCResources/xRemoteAccessServer/xRemoteAccessServer.DSC.Schema.psd1, line 1 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLou35K5o6wCIarjIUm:-KLqIvOtZ99jrxeg4Amk:-499146009) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/DSCLibrary/Modules/MyDSCResources/xRemoteAccessServer/xRemoteAccessServer.DSC.Schema.psd1#L1)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> CRLF here too :smile:
</details>
Done.

---

*[LabBuilder/lib/private/utils.ps1, line 370 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLouLYbGYGjlu0H0yKZ:-KLqIwa9lpV8LZE5-6Y9:-342947145) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/lib/private/utils.ps1#L370)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> I don't think this line is correct. The WSMan service is actually called WinRM. But it won't be able to start unless Remoting has been initialized, which is done by the next command (Set-WSManQuickConfig).
</details>
I have had an issue a number of times where the service is simply not running and quick-config doesn't resolve the issue.  I had put it in to prevent my having to start the service through some other manner.  What I really want to do when I have a chance is to try to start the service, if that fails then run the quick-config - that was just a real quick fix.  

---

*[LabBuilder/lib/public/vm.ps1, line 388 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLowUU99BDcUTSEu2GE:-KLqKG_LxQw-_w7efNri:-499146009) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/lib/public/vm.ps1#L388)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> You can go ahead and delete this whole block if you like - good catch! That is why it is great having a Hyper-V/Cluster expert on this :smile:
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-:-KLqIU8gsBVpvzGZWr1G:672096547)*

**Comment by MS-MatthewWalker** [comment]
Review status: 21 of 31 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[LabBuilder/lib/private/utils.ps1, line 370 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLouLYbGYGjlu0H0yKZ:-KLqWryiLsLekuPo_udp:-578894184) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/lib/private/utils.ps1#L370)):*
<details><summary><i>Previously, MS-MatthewWalker (Matthew L. Walker) wrote…</i></summary>
> I have had an issue a number of times where the service is simply not running and quick-config doesn't resolve the issue.  I had put it in to prevent my having to start the service through some other manner.  What I really want to do when I have a chance is to try to start the service, if that fails then run the quick-config - that was just a real quick fix.  
</details>
ACK - right the service name is incorrect - I'll fix that piece. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/plagueho/labbuilder/256)*

**Comment by PlagueHO** [comment]
I'll finish this review over the weekend. Sorry about the delay sir. Just been a crazy week at work. :(

**Comment by PlagueHO** [comment]
Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[LabBuilder/DSCLibrary/Modules/MyDSCResources/xJoinDomain/xJoinDomain.DSC.Schema.psm1, line 72 \[r2\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KMGpXmvAdAg7zy598__:-KMGpXmvAdAg7zy598_a:1893562055) ([raw file](https://github.com/plagueho/labbuilder/blob/8238e4c4dc5e068cd202e40adcca4d68c4237852/LabBuilder/DSCLibrary/Modules/MyDSCResources/xJoinDomain/xJoinDomain.DSC.Schema.psm1#L72)):*
> ```PowerShell
>         }
>     
> }
> ```

Doh - still missing a CRLF on this one!

---

*[LabBuilder/lib/private/utils.ps1, line 370 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLouLYbGYGjlu0H0yKZ:-KMGpiIdbRJaHCADE4My:-1744304465) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/lib/private/utils.ps1#L370)):*
<details><summary><i>Previously, MS-MatthewWalker (Matthew L. Walker) wrote…</i></summary>
> ACK - right the service name is incorrect - I'll fix that piece. 
</details>
What you could do is:
try
{
Start-Service -Name WinRm -ErrorAction Stop
}
catch
{
 $null = Set-WSManQuickConfig `
            @PSBoundParameters
            -ErrorAction Stop
}

This way if it can't start it'll failover to trying a QC.

---

*[LabBuilder/lib/public/vm.ps1, line 388 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLowUU99BDcUTSEu2GE:-KMGqv9l8XS2TlmN6nYN:-777129057) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/lib/public/vm.ps1#L388)):*
<details><summary><i>Previously, MS-MatthewWalker (Matthew L. Walker) wrote…</i></summary>
> Done.
</details>
Did you commit this change? It doesn't seem to have appeared in the push.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/plagueho/labbuilder/256)*

**Comment by MS-MatthewWalker** [comment]
I'll work on these tonight

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-:-KMQeTuNLfCX7CTtk0uh:-2011902031)*

**Comment by MS-MatthewWalker** [comment]
Review status: 28 of 31 files reviewed at latest revision, 5 unresolved discussions.

---

*[LabBuilder/dsclibrary/MEMBER_BRANCHCACHE_HOST.DSC.ps1, line  \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLot6mMYiL5Jqmw0GRl:-KMU8g9UTYJ4_3p52AZK:-499146009) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/dsclibrary/MEMBER_BRANCHCACHE_HOST.DSC.ps1#L)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Is there a reason this file was deleted? I'm guessing just a mistake somewhere a long the line. Are you able to add it back to your branch?
</details>
Done.

---

*[LabBuilder/dsclibrary/MEMBER_FAILOVERCLUSTER_DHCP.DSC.ps1, line  \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLotLrP4l8JI4xyJ384:-KMU8i_2NkqJIwZsS5kR:-499146009) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/dsclibrary/MEMBER_FAILOVERCLUSTER_DHCP.DSC.ps1#L)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Same with this file - was it deleted by mistake? Or just Git being annoying (which it can be)!
</details>
Done.

---

*[LabBuilder/DSCLibrary/Modules/MyDSCResources/xJoinDomain/xJoinDomain.DSC.Schema.psm1, line 72 \[r2\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KMGpXmvAdAg7zy598__:-KMU8WrauhVdjVRqhIDm:676635175) ([raw file](https://github.com/plagueho/labbuilder/blob/8238e4c4dc5e068cd202e40adcca4d68c4237852/LabBuilder/DSCLibrary/Modules/MyDSCResources/xJoinDomain/xJoinDomain.DSC.Schema.psm1#L72)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Doh - still missing a CRLF on this one!
</details>
Done

---

*[LabBuilder/lib/private/utils.ps1, line 370 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLouLYbGYGjlu0H0yKZ:-KMU8_Gr7fRUg-TBd_wp:-499146009) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/lib/private/utils.ps1#L370)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> What you could do is:
> try
> {
> Start-Service -Name WinRm -ErrorAction Stop
> }
> catch
> {
>  $null = Set-WSManQuickConfig `
>             @PSBoundParameters
>             -ErrorAction Stop
> }
> 
> This way if it can't start it'll failover to trying a QC.
</details>
Done.

---

*[LabBuilder/lib/public/vm.ps1, line 388 \[r1\]](https://reviewable.io:443/reviews/plagueho/labbuilder/256#-KLowUU99BDcUTSEu2GE:-KMU8boazFbXvn054WtL:-499146009) ([raw file](https://github.com/plagueho/labbuilder/blob/5417f62d1126db53ebf46e7de6eaa4d7a003663b/LabBuilder/lib/public/vm.ps1#L388)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Did you commit this change? It doesn't seem to have appeared in the push.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/plagueho/labbuilder/256)*

**Comment by PlagueHO** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/plagueho/labbuilder/256)*

**Pull request merged**
